set_project("demo_xmake_interfaces")
set_version("0.1.0")
set_languages("cxx17")

add_rules("mode.debug", "mode.release")
add_rules("ament_xmake.package")

-- rosidl targets are auto-generated by the colcon-xmake rosidl pipeline
-- and injected via the entry file before this xmake.lua is loaded.
-- No explicit target definitions needed for interface-only packages.

-- Phony target to trigger the install rule
target("demo_xmake_interfaces_marker")
    set_kind("phony")
