set_project("demo_xmake_cpp")
set_version("0.1.0")
set_languages("cxx17")

add_rules("mode.debug", "mode.release")
add_rules("ament_xmake.package")

target("demo_xmake_cpp")
    set_kind("static")
    add_files("src/demo_lib.cpp")
    add_includedirs("include", {public = true})
    add_headerfiles("include/(demo_xmake_cpp/*.hpp)")

target("demo_xmake_cpp_shared")
    set_kind("shared")
    add_files("src/demo_lib.cpp")
    add_includedirs("include", {public = true})
    add_headerfiles("include/(demo_xmake_cpp/*.hpp)")
    add_defines("DEMO_XMAKE_CPP_BUILDING_DLL", {public = false})
    set_basename("demo_xmake_cpp")

target("demo_xmake_cpp_node")
    set_kind("binary")
    set_installdir("lib/demo_xmake_cpp")
    add_files("src/main.cpp", "src/demo_lib.cpp")
    add_includedirs("include")

target("turtle_circle_node")
    set_kind("binary")
    set_installdir("lib/demo_xmake_cpp")
    add_files("src/turtle_circle_node.cpp")
    add_ros_deps("rclcpp", "geometry_msgs")
    add_includedirs("include")
